Rails.application.config.assets.precompile += %w(
                                                  badger/badger.css
                                                  butler/*
                                                  butler/butler.js
                                                  computers/computers.css
                                                  crm/crm.css
                                                  ghostcrime/ghostcrime.css
                                                  go/go.css
                                                  scalequail/quail.js
                                                  scalequail/scalequail.css
                                                  snapback/snapback.css
                                                  store/dealzone.js
                                                  vendor/devrama-book.css
                                                  vendor/jquery.devrama.book.min.js
                                                  vendor/jscolor.min.js
                                                  woods/binarywoods.css
                                                  woods/tree_editor.js
                                                  woods/woods.js
                                                  stocks/stocks.js
                                                  stocks/stocks.css
                                                  melon/melon.css
                                                )
