require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Woods::ItemsetsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Woods::Itemset. As you add validations to Woods::Itemset, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Woods::ItemsetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all woods_itemsets as @itemsets" do
      itemset = Woods::Itemset.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:itemsets)).to eq([itemset])
    end
  end

  describe "GET #show" do
    it "assigns the requested woods_itemset as @itemset" do
      itemset = Woods::Itemset.create! valid_attributes
      get :show, {:id => itemset.to_param}, valid_session
      expect(assigns(:itemset)).to eq(itemset)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Woods::Itemset" do
        expect {
          post :create, {:woods_itemset => valid_attributes}, valid_session
        }.to change(Woods::Itemset, :count).by(1)
      end

      it "assigns a newly created woods_itemset as @itemset" do
        post :create, {:woods_itemset => valid_attributes}, valid_session
        expect(assigns(:itemset)).to be_a(Woods::Itemset)
        expect(assigns(:itemset)).to be_persisted
      end

      it "redirects to the created woods_itemset" do
        post :create, {:woods_itemset => valid_attributes}, valid_session
        expect(response).to redirect_to(Woods::Itemset.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved woods_itemset as @itemset" do
        post :create, {:woods_itemset => invalid_attributes}, valid_session
        expect(assigns(:itemset)).to be_a_new(Woods::Itemset)
      end

      it "re-renders the 'new' template" do
        post :create, {:woods_itemset => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested woods_itemset" do
      itemset = Woods::Itemset.create! valid_attributes
      expect {
        delete :destroy, {:id => itemset.to_param}, valid_session
      }.to change(Woods::Itemset, :count).by(-1)
    end

    it "redirects to the woods_itemsets list" do
      itemset = Woods::Itemset.create! valid_attributes
      delete :destroy, {:id => itemset.to_param}, valid_session
      expect(response).to redirect_to(woods_itemsets_url)
    end
  end

end
