require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Woods::NodesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Woods::Node. As you add validations to Woods::Node, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Woods::NodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested woods_node" do
        node = Woods::Node.create! valid_attributes
        put :update, {:id => node.to_param, :woods_node => new_attributes}, valid_session
        node.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested woods_node as @node" do
        node = Woods::Node.create! valid_attributes
        put :update, {:id => node.to_param, :woods_node => valid_attributes}, valid_session
        expect(assigns(:node)).to eq(node)
      end

      it "redirects to the woods_node" do
        node = Woods::Node.create! valid_attributes
        put :update, {:id => node.to_param, :woods_node => valid_attributes}, valid_session
        expect(response).to redirect_to(node)
      end
    end

    context "with invalid params" do
      it "assigns the woods_node as @node" do
        node = Woods::Node.create! valid_attributes
        put :update, {:id => node.to_param, :woods_node => invalid_attributes}, valid_session
        expect(assigns(:node)).to eq(node)
      end

      it "re-renders the 'edit' template" do
        node = Woods::Node.create! valid_attributes
        put :update, {:id => node.to_param, :woods_node => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

end
