require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Woods::PaintballsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Woods::Paintball. As you add validations to Woods::Paintball, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Woods::PaintballsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all woods_paintballs as @paintballs" do
      paintball = Woods::Paintball.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:paintballs)).to eq([paintball])
    end
  end

  describe "GET #show" do
    it "assigns the requested woods_paintball as @paintball" do
      paintball = Woods::Paintball.create! valid_attributes
      get :show, {:id => paintball.to_param}, valid_session
      expect(assigns(:paintball)).to eq(paintball)
    end
  end

  describe "GET #new" do
    it "assigns a new woods_paintball as @paintball" do
      get :new, {}, valid_session
      expect(assigns(:paintball)).to be_a_new(Woods::Paintball)
    end
  end

  describe "GET #edit" do
    it "assigns the requested woods_paintball as @paintball" do
      paintball = Woods::Paintball.create! valid_attributes
      get :edit, {:id => paintball.to_param}, valid_session
      expect(assigns(:paintball)).to eq(paintball)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Woods::Paintball" do
        expect {
          post :create, {:woods_paintball => valid_attributes}, valid_session
        }.to change(Woods::Paintball, :count).by(1)
      end

      it "assigns a newly created woods_paintball as @paintball" do
        post :create, {:woods_paintball => valid_attributes}, valid_session
        expect(assigns(:paintball)).to be_a(Woods::Paintball)
        expect(assigns(:paintball)).to be_persisted
      end

      it "redirects to the created woods_paintball" do
        post :create, {:woods_paintball => valid_attributes}, valid_session
        expect(response).to redirect_to(Woods::Paintball.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved woods_paintball as @paintball" do
        post :create, {:woods_paintball => invalid_attributes}, valid_session
        expect(assigns(:paintball)).to be_a_new(Woods::Paintball)
      end

      it "re-renders the 'new' template" do
        post :create, {:woods_paintball => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested woods_paintball" do
        paintball = Woods::Paintball.create! valid_attributes
        put :update, {:id => paintball.to_param, :woods_paintball => new_attributes}, valid_session
        paintball.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested woods_paintball as @paintball" do
        paintball = Woods::Paintball.create! valid_attributes
        put :update, {:id => paintball.to_param, :woods_paintball => valid_attributes}, valid_session
        expect(assigns(:paintball)).to eq(paintball)
      end

      it "redirects to the woods_paintball" do
        paintball = Woods::Paintball.create! valid_attributes
        put :update, {:id => paintball.to_param, :woods_paintball => valid_attributes}, valid_session
        expect(response).to redirect_to(paintball)
      end
    end

    context "with invalid params" do
      it "assigns the woods_paintball as @paintball" do
        paintball = Woods::Paintball.create! valid_attributes
        put :update, {:id => paintball.to_param, :woods_paintball => invalid_attributes}, valid_session
        expect(assigns(:paintball)).to eq(paintball)
      end

      it "re-renders the 'edit' template" do
        paintball = Woods::Paintball.create! valid_attributes
        put :update, {:id => paintball.to_param, :woods_paintball => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested woods_paintball" do
      paintball = Woods::Paintball.create! valid_attributes
      expect {
        delete :destroy, {:id => paintball.to_param}, valid_session
      }.to change(Woods::Paintball, :count).by(-1)
    end

    it "redirects to the woods_paintballs list" do
      paintball = Woods::Paintball.create! valid_attributes
      delete :destroy, {:id => paintball.to_param}, valid_session
      expect(response).to redirect_to(woods_paintballs_url)
    end
  end

end
