require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Woods::PalettesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Woods::Palette. As you add validations to Woods::Palette, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Woods::PalettesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all woods_palettes as @palettes" do
      palette = Woods::Palette.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:palettes)).to eq([palette])
    end
  end

  describe "GET #show" do
    it "assigns the requested woods_palette as @palette" do
      palette = Woods::Palette.create! valid_attributes
      get :show, {:id => palette.to_param}, valid_session
      expect(assigns(:palette)).to eq(palette)
    end
  end

  describe "GET #new" do
    it "assigns a new woods_palette as @palette" do
      get :new, {}, valid_session
      expect(assigns(:palette)).to be_a_new(Woods::Palette)
    end
  end

  describe "GET #edit" do
    it "assigns the requested woods_palette as @palette" do
      palette = Woods::Palette.create! valid_attributes
      get :edit, {:id => palette.to_param}, valid_session
      expect(assigns(:palette)).to eq(palette)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Woods::Palette" do
        expect {
          post :create, {:woods_palette => valid_attributes}, valid_session
        }.to change(Woods::Palette, :count).by(1)
      end

      it "assigns a newly created woods_palette as @palette" do
        post :create, {:woods_palette => valid_attributes}, valid_session
        expect(assigns(:palette)).to be_a(Woods::Palette)
        expect(assigns(:palette)).to be_persisted
      end

      it "redirects to the created woods_palette" do
        post :create, {:woods_palette => valid_attributes}, valid_session
        expect(response).to redirect_to(Woods::Palette.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved woods_palette as @palette" do
        post :create, {:woods_palette => invalid_attributes}, valid_session
        expect(assigns(:palette)).to be_a_new(Woods::Palette)
      end

      it "re-renders the 'new' template" do
        post :create, {:woods_palette => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested woods_palette" do
        palette = Woods::Palette.create! valid_attributes
        put :update, {:id => palette.to_param, :woods_palette => new_attributes}, valid_session
        palette.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested woods_palette as @palette" do
        palette = Woods::Palette.create! valid_attributes
        put :update, {:id => palette.to_param, :woods_palette => valid_attributes}, valid_session
        expect(assigns(:palette)).to eq(palette)
      end

      it "redirects to the woods_palette" do
        palette = Woods::Palette.create! valid_attributes
        put :update, {:id => palette.to_param, :woods_palette => valid_attributes}, valid_session
        expect(response).to redirect_to(palette)
      end
    end

    context "with invalid params" do
      it "assigns the woods_palette as @palette" do
        palette = Woods::Palette.create! valid_attributes
        put :update, {:id => palette.to_param, :woods_palette => invalid_attributes}, valid_session
        expect(assigns(:palette)).to eq(palette)
      end

      it "re-renders the 'edit' template" do
        palette = Woods::Palette.create! valid_attributes
        put :update, {:id => palette.to_param, :woods_palette => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested woods_palette" do
      palette = Woods::Palette.create! valid_attributes
      expect {
        delete :destroy, {:id => palette.to_param}, valid_session
      }.to change(Woods::Palette, :count).by(-1)
    end

    it "redirects to the woods_palettes list" do
      palette = Woods::Palette.create! valid_attributes
      delete :destroy, {:id => palette.to_param}, valid_session
      expect(response).to redirect_to(woods_palettes_url)
    end
  end

end
