production:
  host: <%= ENV["CHRISTIANRAILS_DBSERVER_PROD"] %>
  adapter: postgresql
  database: christianrails_prod
  pool: 5
  timeout: 5000
  username: <%= ENV["CHRISTIANRAILS_DBUSER_PROD"] %>
  password: <%= ENV["CHRISTIANRAILS_DBPASS_PROD"] %>

development:
  host: <%= ENV["CHRISTIANRAILS_DBSERVER_DEV"] %>
  adapter: postgresql
  database: christianrails_dev
  pool: 5
  timeout: 5000
  username: <%= ENV["CHRISTIANRAILS_DBUSER_DEV"] %>
  password: <%= ENV["CHRISTIANRAILS_DBPASS_DEV"] %>

test:
  host: <%= ENV["CHRISTIANRAILS_DBSERVER_DEV"] %>
  adapter: postgresql
  database: christianrails_test
  pool: 5
  timeout: 5000
  username: <%= ENV["CHRISTIANRAILS_DBUSER_DEV"] %>
  password: <%= ENV["CHRISTIANRAILS_DBPASS_DEV"] %>